
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: demochat
  labels:
    deploy: devtest
    service: demochat
    app: demochat
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        forceRedeployUniqId: "{{CF_REVISION}}"
      labels:
        deploy: devtest
        service: demochat
    spec:
      containers:
      - image: itnewsbox/demochat:{{CF_BRANCH}}
        name: demochat
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          protocol: TCP
---
  apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    labels:
      deploy: devtest
    name: demochat-ingress
  spec:
    backend:
      serviceName: demochat-board
      servicePort: 80
---
  apiVersion: v1
  kind: Service
  metadata:
    labels:
      deploy: test1
    name: demochat-master
  spec:
    type: NodePort
    selector:
      app: demochat
    ports:
    - name: "http"
      port: 80
      protocol: TCP
      targetPort: 5000
    selector:
      service: demochat-board
